# basic python

In [1]:
# make a function that calculates the summation of two or three numbers
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


In [2]:
#make a calculator that takes two number and does subtraction depending on the function
def do_math(a, b, kind=' '):
    if (kind=='subtract'):
        return a-b
    elif (kind=='add'):
        return a+b
    else:
        return a*b # when kind == ' '

do_math(1, 2)

2

In [3]:
#Tuples are an immutable data structure (cannot be altered).
x = (1, 'a', 2, 'b') #type(x)
#Lists are a mutable data structure.
y = [1, 'a', 2, 'b'] #type(y)
#add a number to the list
y.append(3.3)
print(y)

[1, 'a', 2, 'b', 3.3]


In [4]:
#looping through lists
#using for
for item in y:
    print(item)

1
a
2
b
3.3


In [5]:
#indexing or using while
i=0
while( i != len(y) ):
    print(y[i])
    i = i + 1

1
a
2
b
3.3


In [6]:
# + to concatenate lists.
[1,2] + [3,4]

[1, 2, 3, 4]

In [7]:
#* to repeat lists
[1, 2, 3, 4]*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [8]:
x = 'This is a string'
print(x[0]) #first character
print(x[0:1]) #first character, but we have explicitly set the end character
print(x[0:2]) #first two characters
print(x[-1]) #return the last element of the string
print(x[-4:-2]) #return the slice starting from the 4th element from the end and stopping before the 2nd element from the end.
print(x[:4]) #from the beginning of the string and stopping before the 3rd element.
print(x[4:])

T
T
Th
g
ri
This
 is a string


In [9]:
firstname = 'Fahim'
lastname = 'Alam'

print(firstname + ' ' + lastname)

Fahim Alam


In [10]:
firstname = 'MD Fahim Sahariar Alam'.split(' ')[0] # [0] selects the first element of the list
lastname = 'MD Fahim Sahariar Alam'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

MD
Alam


In [11]:
'abir'+'29793'

'abir29793'

In [12]:
#dictionaries
x = {'Fahim Alam': 'abir29793h@uvic.ca', 'Shazia Zaman': 'shazia.zaman2111@gmail.com'}
x['Fahim Alam'] # Retrieve a value by using the indexing operator

'abir29793h@uvic.ca'

In [13]:
for name in x:
    print(name)

Fahim Alam
Shazia Zaman


In [14]:
for email in x.values():
    print(email)

abir29793h@uvic.ca
shazia.zaman2111@gmail.com


In [15]:
for name, email in x.items():
    print(name,email)

Fahim Alam abir29793h@uvic.ca
Shazia Zaman shazia.zaman2111@gmail.com


In [16]:
#unpack the data
#Make sure the number of values you are unpacking matches the number of variables being assigned.
x = ('Fahim', 'Alam', 'abir29793h@uvic.ca')
fname, lname, email = x
print(lname,fname)

Alam Fahim


In [17]:
#string Formatting
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Fahim'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

Fahim bought 4 item(s) at a price of 3.24 each for a total of 12.96


 # Reading and Writing CSV files

In [18]:
import csv
%precision 2

'%.2f'

In [19]:
with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))

    
mpg[:3] # The first three dictionaries in our list.

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [20]:
#`csv.Dictreader` has read in each row of our csv file as a dictionary.
#`len` shows that our list is comprised of 234 dictionaries.
len(mpg)

234

In [21]:
# `keys` gives us the column names of our csv.
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [22]:
# to find the average cty fuel economy across all cars.
# All values in the dictionaries are strings, so we need to convert to float.
sum(float(item['cty'])for item in mpg)/len(mpg)

16.86

In [23]:
max(item['cyl']for item in mpg)

'8'

In [24]:
# we are grouping the cars by number of cylinder, and finding the average cty mpg for each group.
cylinders = set(d['cyl'] for d in mpg)
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [25]:
# to find the average hwy mpg for each class of vehicle in our dataset.
vehicleclass = set(d['class'] for d in mpg) # what are the class types
HwyMpgByClass= []
for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the cylinder amount type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

#  Dates and Times

In [26]:
import datetime as dt
import time as tm

In [27]:
# time returns the current time in seconds since the Epoch. (January 1st, 1970)
tm.time()

1614382478.85

In [28]:
# lets convert the abo
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2021, 2, 26, 15, 34, 38, 866074)

In [29]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2021, 2, 26, 15, 34, 38)

In [30]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

datetime.timedelta(days=100)

In [31]:
today = dt.date.today()
today

datetime.date(2021, 2, 26)

# Objects and map()

In [32]:
# name of a class should begin with a capital letter
class Person:
    department = 'School of Maths and Stats' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [33]:
person = Person()
person.set_name('Fahim Alam')
person.set_location('Victoria, BC, Canada')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

Fahim Alam live in Victoria, BC, Canada and works in the department School of Maths and Stats


In [34]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


In [35]:
# write a function and apply it using map() to get a list of all 
#faculty titles and last names (e.g. ['Dr. Brooks', 'Dr. Collins-Thompson', …]) 
people = ['Fahim S Alam', 'Shazia S Zaman', 'Mahi J Alam', 'Afra A Alam']

def split_title_and_name(person):
    title = person.split()[0] # take first name
    lastname = person.split()[-1] #take last name
    return '{} {}'.format(title, lastname)

list(map(split_title_and_name, people))

['Fahim Alam', 'Shazia Zaman', 'Mahi Alam', 'Afra Alam']

#  Lambda and List Comprehensions

In [36]:
#  lambda that takes in three parameters and adds the first two.
my_function = lambda a, b, c : a + b
my_function(1, 2, 3)

3

In [37]:
#lets call the previous example and map it
people = ['Fahim S Alam', 'Shazia S Zaman', 'Mahi J Alam', 'Afra A Alam']
list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

['Fahim Alam', 'Shazia Zaman', 'Mahi Alam', 'Afra Alam']

In [38]:
# do the same thing without mapping
for person in people:
    print((lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

Fahim Alam
Shazia Zaman
Mahi Alam
Afra Alam


In [39]:
# iterate from 0 to 999 and return the even numbers.
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
#my_list

In [40]:
# the same thing but with list comprehension i.e doing the iteration in one line
my_list = [number for number in range(0,1000) if number % 2 == 0]
#my_list

In [41]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst
#times_tables()

In [42]:
# do the same thing with list comprehension
lst = [j*i for i in range(10) for j in range(10)]
#lst

Many organizations have user ids which are constrained in some way. Imagine you work at an internet service provider and the user ids are all two letters followed by two numbers (e.g. aa49). Your task at such an organization might be to hold a record on the billing activity for each possible user.

Write an initialization line as a single list comprehension which creates a list of all possible user ids. Assume the letters are all lower case.

In [43]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

correct_answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]

#correct_answer[:50] # Display first 50 ids

# Numerical Python (NumPy) 

In [44]:
import numpy as np

In [45]:
# another way to create arrays by passing the lists directly
y = np.array([4, 5, 6])
#y

In [46]:
# Get Size
y.itemsize

4

In [47]:
# Get number of elements
y.size

3

In [48]:
 # Create a list and convert it to a numpy array
my_list = np.array([1,2,3], dtype='int32')
x = np.array(my_list)
#x

In [49]:
# put list in a list to create multidimensional arrays
m = np.array([[7, 8, 9], [10, 11, 12]])
#m

In [50]:
# arange returns evenly spaced values within a given interval.
n = np.arange(0, 30, 4) # start at 0 count up by 4, stop before 30
n

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [51]:
# get the size
x.shape

(3,)

In [52]:
# Get Dimension
x.ndim

1

In [53]:
n = n.reshape(2, 4) # reshape array to be 2x4 #o.resize(r,c)
n

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28]])

In [54]:
# linspace returns evenly spaced numbers over a specified interval.
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [55]:
# Any other number
np.full((3,2), 99,dtype='int32')

array([[99, 99],
       [99, 99],
       [99, 99]])

In [56]:
# ones returns a new array of given shape and type, filled with ones
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [57]:
np.zeros((1,2))

array([[0., 0.]])

In [58]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.7258589 , 0.28737657],
       [0.86304663, 0.31950864],
       [0.82651461, 0.84711471],
       [0.23352289, 0.62893245]])

In [60]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-1,  3,  1],
       [-1,  0,  5],
       [ 0,  3,  1]])

In [61]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [62]:
m= [1,2]
np.diag(m)

array([[1, 0],
       [0, 2]])

In [63]:
np.tile(m,2) # does same thing as [1,2]*2

array([1, 2, 1, 2])

In [64]:
np.repeat([1, 2], 2)

array([1, 1, 2, 2])

In [65]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [66]:
# Use vstack to stack arrays in sequence vertically (row wise).
# Use `hstack` to stack arrays in sequence horizontally (column wise).
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [67]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [68]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

2


In [69]:
# we will transpose the matrix z, lets see the current size 
#z.shape
z.T
# see the size also changed 
#z.T.shape

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

Use `.dtype` to see the data type of the elements in the array.
<br>
z.dtype
<br>
Use `.astype` to cast to a specific type.

In [70]:
z = z.astype('f')
z.dtype

dtype('float32')

In [71]:
a = np.array([-4, -2, 1, 3, 5])
# `argmax` and `argmin` return the index of the maximum and minimum values in the array.
a.argmin()

0

In [72]:
# Indexing / Slicing
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [73]:
s[0], s[4], s[-1],s[1:5]

(0, 16, 144, array([ 1,  4,  9, 16], dtype=int32))

In [74]:
r = np.arange(36)
r.resize((6, 6))

In [75]:
r[3, 3:6] # use : to select a range of rows or columns

array([21, 22, 23])

In [76]:
# Python program explaining  
# where() function  
  
import numpy as np 
  
# a is an array of integers. 
a = np.array([[1, 2, 3], [4, 5, 6]]) 
  
print(a) 
  
print ('Indices of elements <4') 
  
b = np.where(a<4) 
print(b) 
  
print("Elements which are <4") 
print(a[b]) 

[[1 2 3]
 [4 5 6]]
Indices of elements <4
(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))
Elements which are <4
[1 2 3]


In [77]:
# create a matrix with some random elements
test = np.random.randint(0, 10, (4,3))
test

array([[3, 2, 7],
       [5, 9, 0],
       [5, 5, 6],
       [5, 7, 6]])

In [78]:
# iterate by row
for row in test:
    print(row)

[3 2 7]
[5 9 0]
[5 5 6]
[5 7 6]


In [79]:
# iterate by index
for i in range(len(test)):
    print(test[i])

[3 2 7]
[5 9 0]
[5 5 6]
[5 7 6]


In [80]:
# iterate by row,index
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [3 2 7]
row 1 is [5 9 0]
row 2 is [5 5 6]
row 3 is [5 7 6]


In [81]:
test2 = test**2
test2

array([[ 9,  4, 49],
       [25, 81,  0],
       [25, 25, 36],
       [25, 49, 36]], dtype=int32)

In [82]:
# Use zip to iterate over multiple iterables.
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[3 2 7] + [ 9  4 49] = [12  6 56]
[5 9 0] + [25 81  0] = [30 90  0]
[5 5 6] + [25 25 36] = [30 30 42]
[5 7 6] + [25 49 36] = [30 56 42]


In [83]:
c = np.array([[1, 2, 3], [4, 5, 6],[2, 1, 4]]) 
#c[0:3,::-4] # get  the 3rd column
c[:,::-4]  # get the 3rd column
c.reshape(9)[::4] # get the diagonal entries

array([1, 5, 4])